# Generated by Django 5.1.1 on 2024-09-11 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LandDocument',
            fields=[
                ('document_id', models.AutoField(primary_key=True, serialize=False)),
                ('parcel_Number', models.CharField(default='', max_length=50)),
                ('national_id', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('owner_name', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=30)),
                ('date_sold', models.DateField(max_length=15)),
            ],
        ),
    ]
