# Generated by Django 5.1.1 on 2024-09-09 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LandDetails',
            fields=[
                ('land_details_id', models.SmallIntegerField(unique=True)),
                ('parcel_number', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True)),
                ('property_address', models.CharField(max_length=30)),
                ('date_acquired', models.DateField()),
                ('land_Description', models.TextField(default='No description provided')),
                ('price', models.FloatField(default=0.0)),
                ('owner_name', models.CharField(max_length=25)),
                ('previous_owner', models.CharField(max_length=30)),
                ('date_sold', models.DateField()),
                ('date_purchased', models.DateField()),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
            ],
        ),
    ]
