# Generated by Django 5.1.1 on 2024-09-09 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landDetails', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landdetails',
            name='land_details_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='landdetails',
            name='parcel_number',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
