# Generated by Django 5.1.1 on 2024-09-11 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landDetails', '0002_alter_landdetails_land_details_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='landdetails',
            old_name='property_address',
            new_name='address',
        ),
        migrations.RemoveField(
            model_name='landdetails',
            name='date_purchased',
        ),
        migrations.AddField(
            model_name='landdetails',
            name='national_id',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='landdetails',
            name='date_sold',
            field=models.DateField(max_length=15),
        ),
    ]
